abc_finder/config/routes.rb
Rails.application.routes.draw do
  post "letters/:id/addlang", to: "letters#addlang"
  resources :languages, except: [:destroy]
  resources :letters, except: [:destroy]
  resources :languageletters, except: [:destroy]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

abc_finder/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

abc_finder/app/models/language.rb
class Language < ApplicationRecord
    has_many :language_letters
    has_many :letters, through: :language_letters
end

abc_finder/app/models/language_letter.rb
class LanguageLetter < ApplicationRecord
    belongs_to :language
    belongs_to :letter
end

abc_finder/app/models/letter.rb
class Letter < ApplicationRecord
    has_many :language_letters
    has_many :languages, through: :language_letters
end

abc_finder/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

abc_finder/app/controllers/language_letters_controller.rb
class LanguageLettersController < ApplicationController
  def index
  end

  def show
  end

  def new
  end

  def create
  end

  def edit
  end

  def update
  end

end

abc_finder/app/controllers/languages_controller.rb
class LanguagesController < ApplicationController
  
  before_action :find_instance, only: [:show, :edit, :update]
  def index
    @languages = Language.all
  end

  def show
  end

  def new
    @language = Language.new
  end

  def create

    language = Language.create(language_params(:name))
    redirect_to language_path(language)
  end

  def edit
  end

  def update
    @language.update(language_params(:name))
    redirect_to language_path(@language)
  end

  private

  def find_instance
    @language = Language.find(params[:id])
  end

  def language_params(*args)
    params.require(:language).permit(*args)
  end
end

abc_finder/app/controllers/letters_controller.rb
class LettersController < ApplicationController
  
  before_action :find_letter, only: [:show, :edit, :update]
  before_action :find_language_id, only: [:show]

  def index
    @letters = Letter.all.order(character_code: :asc)
  end

  def show
  end

  def new
    @letter = Letter.new
  end

  def create
    params[:letter][:character_code] = params[:letter][:character_code].ord
    @letter = Letter.create(letter_params(:character_code, :alphabet_type))
    LanguageLetter.create(language_id: params[:letter][:languages][:language_id], letter_id: @letter.id)
    redirect_to letter_path(@letter)
  end

  def edit
    @letter.character_code = @letter.character_code.chr
  end

  def update
    @letter.update(letter_params(:alphabet_type))
    redirect_to letter_path(@letter)
  end

  def addlang
    LanguageLetters.find_or_create_by(language_id: [:language][:language_id], letter_id: params[:id])
    redirect_to letters_path
  end

  private
  def find_letter
    @letter = Letter.find(params[:id])
  end

  def letter_params(*args)
    params.require(:letter).permit(*args)
  end

  def find_language_id
    @languages = Language.all
  end


end

abc_finder/app/helpers/application_helper.rb
module ApplicationHelper
end

abc_finder/app/helpers/language_letters_helper.rb
module LanguageLettersHelper
end

abc_finder/app/helpers/languages_helper.rb
module LanguagesHelper
end

abc_finder/app/helpers/letters_helper.rb
module LettersHelper
end

abc_finder/app/views/language_letters/edit.html.erb
<h1>LanguageLetters#edit</h1>
<p>Find me in app/views/language_letters/edit.html.erb</p>

abc_finder/app/views/language_letters/index.html.erb
<h1>LanguageLetters#index</h1>
<p>Find me in app/views/language_letters/index.html.erb</p>

abc_finder/app/views/language_letters/new.html.erb
<h1>LanguageLetters#new</h1>
<p>Find me in app/views/language_letters/new.html.erb</p>

abc_finder/app/views/language_letters/show.html.erb
<h1>LanguageLetters#show</h1>
<p>Find me in app/views/language_letters/show.html.erb</p>

abc_finder/app/views/languages/_language_form.html.erb
<%= form_for @language do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <%= f.submit %>
<% end %>

abc_finder/app/views/languages/edit.html.erb
<%= render partial: "language_form" %>

abc_finder/app/views/languages/index.html.erb
<h1> Languages </h1>

<ul>
    <%@languages.each do |lang|%>
        <li><%= link_to lang.name, language_path(lang)%></li>
    <% end %>
</ul>

<%= link_to "Create a new language", new_language_path%>

abc_finder/app/views/languages/new.html.erb
<%= render partial: "language_form" %>

abc_finder/app/views/languages/show.html.erb
<h1> <%= @language.name%> </h1>

<ol>
    <% @language.letters.each do |let|%>
        <li><%= link_to let.character_code.chr, letter_path(let)%></li>
    <% end %>
</ol> 

<%= link_to "Go back to the Index page", languages_path %>

abc_finder/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AbcFinder</title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

abc_finder/app/views/letters/_letter_form.html.erb
<%= form_for @letter do |f| %>
    <%= f.label :character_code, "Enter a Character: " %>
    <%= f.text_field :character_code %>
    <%= f.label :alphabet_type %>
    <%= f.text_field :alphabet_type %>

    <%= f.fields_for :languages do |l| %>
        <%= l.label :name %>
        <%= l.collection_select :language_id, Language.all, :id, :name, {prompt: "Choose a Language!!"}%>
    <% end %>

    <%= f.submit %>
<% end %>

abc_finder/app/views/letters/edit.html.erb
<%= render partial: "letter_form" %>

abc_finder/app/views/letters/index.html.erb
<h1> Letters </h1>

<ul>
    <%@letters.each do |let|%>
        <li><%= link_to let.character_code.chr(Encoding::UTF_8), letter_path(let)%></li>
    <% end %>
</ul>

<%= link_to "Create a new letter", new_letter_path%>

abc_finder/app/views/letters/new.html.erb
<%= render partial: "letter_form" %>

abc_finder/app/views/letters/show.html.erb
<h1> <%= @letter.character_code.chr(Encoding::UTF_8)%> </h1>
<%= @letter.alphabet_type%>

<ol>
    <% @letter.languages.each do |lang|%>
        <li><%= link_to lang.name, language_path(lang)%></li>
    <% end %>
</ol> 

<h4> Add a new Language </h4>

<%=form_tag "letters/:id/addlang" do %>
    <label for="lang"> Language </label>
    <%= select_tag :language_id, options_from_collection_for_select(Language.all, "id", "name") %> 
    <%= submit_tag "Add a lang"%>    
<% end %>


<%= link_to "Go back to the Index page", letters_path %>